### ISSUE TITLE
Is it possible to modify the template of the tag?

### ISSUE THREAD

**Issue by wsw70** [mdlockyer/PrintTags#1]
First of all: thanks for your cool library I just discovered.

Is it possible to change the template of the tag, so that instead of 

`[error] something went wrong`

it displays

`13:30 [error] something went wrong`

where the `13:30 [error]` is configured as a template?

**Comment by mdlockyer** [comment]
Not currently, but this is a great idea. Will definitely work on adding this in the near future

**Comment by mdlockyer** [comment]
The 13:30 you have at the front is a timestamp I take it? Would you be interested in having that added as an optional feature? to add those automatically?

**Comment by wsw70** [comment]
It would be wonderful to be able to template it. I use `arrow` for all date handling and would probably have `arrow.now().isoformat()` there, but sometimes a formatted version would be useful as well.

**Comment by mdlockyer** [comment]
I think this will be the next feature I add. I'm thinking of setting this up as a module that can register user created templates. Once they are registered they will be accessible from anywhere else in the project (e.g. different python files that also import PrintTags) at runtime. This way users can just create the template once and then call something like: 
`pt.from_template('Something to print', template='my_template')`

We could also have the ability to just set a default template as well to remove the need to specify a template for every print. I would like to add an `add_timestamp` argument to the tagged prints that is separate from the templating and will probably just support a default format to keep it simple. But perhaps using a template users could specify further formatting options. Any thoughts are appreciated!

**Comment by mdlockyer** [comment]
Going to close this. Feel free to reopen if you have any suggestions

**Comment by wsw70** [comment]
>  We could also have the ability to just set a default template as well to remove the need to specify a template for every print.

That would be good, otherwise the boilerplate needed to print something would start top be quite large. 

Thanks for taking my suggestion into consideration!
